### ISSUE TITLE
Custom theme does not work

### ISSUE THREAD

**Issue by rush-levint** [DocSpring/craco-antd#3]
https://github.com/FormAPI/craco-antd/blob/093f672d29a43f1b2060c4393131500be69353a7/lib/craco-antd.js#L59

Setting the value of `style` to **true** makes it work.

**Comment by ndbroadbent** [comment]
Oh, sorry about that! That’s just because I was following the [Ant Design docs](https://ant.design/docs/react/use-with-create-react-app), which had `style: ‘css’`. Maybe that worked with an older version.

[This article looks a bit better.](https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f). I’ll also add the `less-vars-to-js` package and support `antd.customize.less`. That’s a bit nicer than using JSON.

**Comment by rush-levint** [comment]
The documentation still holds true for that case as mentioned in the [Customize Theme](https://ant.design/docs/react/use-with-create-react-app#Customize-Theme) section.

**Comment by ndbroadbent** [comment]
OH now that makes sense. Thanks!
